version: "3"

services:
  sse-jobs:
    dns: 8.8.8.8
    build:
      context: ./jobserver/sse-fiuni-jobs/
    restart: "no"
    ports:
      - "8081:80"
    volumes:
      - ./:/mainroot
      - ./jobserver/sse-fiuni-jobs:/var/www/html/jobs
      - ./webserver/sse-fiuni/app/Models:/var/www/html/jobs/app/Models
      - ./webserver/sse-fiuni/config:/var/www/html/jobs/config
      - ./jobserver/sse-fiuni-jobs/conf.d:/etc/supervisor/conf.d
   # entrypoint: [ "bash", "-c", "service supervisor start"]
    depends_on:
      - db
    extra_hosts:
      - "ssej.loc:127.0.0.1"
  sse-web:
    dns: 8.8.8.8
    build:
      context: ./webserver/sse-fiuni/
    restart: "no"
    ports:
      - "80:80"
    volumes:
      - ./:/mainroot
      - ./webserver/sse-fiuni:/var/www/html/webserver
    depends_on:
      - db
    extra_hosts:
      - "sse.loc:127.0.0.1"
  db:
    image: mariadb
    restart: "no"
    ports: #quitar eso para restringir el acceso externo en produccion
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8080:8080
    depends_on:
      - db